openapi: 3.0.0
info:
  title: Orders API
  description: API for managing orders
  version: 0.1.9
servers:
  - url: http://localhost/v1
paths:
  /orders:
    get:
      summary: Returns a list of orders.
      responses:
        '200':
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Order'
    post:
      summary: Creates a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses: 
        '201':
          description: Created

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
        name:
          type: string
          example: Arthur Dent
      required:  
        - id
        - name
