openapi: 3.0.0
info:
  title: Orders API
  description: API for managing orders
  version: 0.1.9
servers:
  - url: http://localhost/v1
paths:
  /orders:
    get:
      summary: Returns a list of orders.
      responses:
        '200':
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Order'
    post:
      summary: Creates a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses: 
        '201':
          description: Created
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          x-go-type: myuuid.UUID
          x-go-type-import:
            name: myuuid
            path: github.com/google/uuid
        name:
          type: string
          example: Arthur Dent
        user_id:
          x-go-type: myuuid.UUID
          x-go-type-import:
            name: myuuid
            path: github.com/google/uuid
      required:  
        - name
        - user_id
