version: "2"

services:
  app:
    image: golang:1.20-alpine
    depends_on:
      - kafka
    volumes:
      - ./:/usr/src/app

  kafka:
    image: docker.io/bitnami/kafka:3.4
    hostname: "localhost"
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local
