// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

import (
	myuuid "github.com/google/uuid"
)

// Order defines model for Order.
type Order struct {
	Id   myuuid.UUID `json:"id"`
	Name string      `json:"name"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = Order
