// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sysradium/petproject/email-notifier/internal/app"
	"github.com/sysradium/petproject/email-notifier/internal/providers"
)

// Injectors from wire.go:

func Initialize() (*app.App, error) {
	loggerAdapter := providers.ProvideLogger()
	router, err := providers.ProvideRouter(loggerAdapter)
	if err != nil {
		return nil, err
	}
	subscriber, err := providers.ProvideSubscriber(loggerAdapter)
	if err != nil {
		return nil, err
	}
	sender := providers.ProvideEmailNotifier()
	eventHandlers := providers.ProvideEventHandlers(sender)
	appApp := app.New(router, subscriber, eventHandlers)
	return appApp, nil
}
