// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: server/v1/server.proto

package serverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GreeterService_SayHello_FullMethodName     = "/server.v1.GreeterService/SayHello"
	GreeterService_PullMessages_FullMethodName = "/server.v1.GreeterService/PullMessages"
)

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterServiceClient interface {
	SayHello(ctx context.Context, in *GreeterServiceSayHelloRequest, opts ...grpc.CallOption) (*GreeterServiceSayHelloResponse, error)
	PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (GreeterService_PullMessagesClient, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) SayHello(ctx context.Context, in *GreeterServiceSayHelloRequest, opts ...grpc.CallOption) (*GreeterServiceSayHelloResponse, error) {
	out := new(GreeterServiceSayHelloResponse)
	err := c.cc.Invoke(ctx, GreeterService_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (GreeterService_PullMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterService_ServiceDesc.Streams[0], GreeterService_PullMessages_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServicePullMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_PullMessagesClient interface {
	Recv() (*GreeterServicePullMessagesResponse, error)
	grpc.ClientStream
}

type greeterServicePullMessagesClient struct {
	grpc.ClientStream
}

func (x *greeterServicePullMessagesClient) Recv() (*GreeterServicePullMessagesResponse, error) {
	m := new(GreeterServicePullMessagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServiceServer is the server API for GreeterService service.
// All implementations must embed UnimplementedGreeterServiceServer
// for forward compatibility
type GreeterServiceServer interface {
	SayHello(context.Context, *GreeterServiceSayHelloRequest) (*GreeterServiceSayHelloResponse, error)
	PullMessages(*PullMessagesRequest, GreeterService_PullMessagesServer) error
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnimplementedGreeterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (UnimplementedGreeterServiceServer) SayHello(context.Context, *GreeterServiceSayHelloRequest) (*GreeterServiceSayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServiceServer) PullMessages(*PullMessagesRequest, GreeterService_PullMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method PullMessages not implemented")
}
func (UnimplementedGreeterServiceServer) mustEmbedUnimplementedGreeterServiceServer() {}

// UnsafeGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServiceServer will
// result in compilation errors.
type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}

func RegisterGreeterServiceServer(s grpc.ServiceRegistrar, srv GreeterServiceServer) {
	s.RegisterService(&GreeterService_ServiceDesc, srv)
}

func _GreeterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreeterServiceSayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHello(ctx, req.(*GreeterServiceSayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_PullMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).PullMessages(m, &greeterServicePullMessagesServer{stream})
}

type GreeterService_PullMessagesServer interface {
	Send(*GreeterServicePullMessagesResponse) error
	grpc.ServerStream
}

type greeterServicePullMessagesServer struct {
	grpc.ServerStream
}

func (x *greeterServicePullMessagesServer) Send(m *GreeterServicePullMessagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// GreeterService_ServiceDesc is the grpc.ServiceDesc for GreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.v1.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreeterService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullMessages",
			Handler:       _GreeterService_PullMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/v1/server.proto",
}
