name: Orders API

on:
  push:
    paths:
      - 'orders-api/**'

jobs:
  build:
    working-directory: orders-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Build
        run: make build

      - name: Test
        run: make test
