name: Users API

on:
  push:
    paths:
      - 'users-api/**'

jobs:
  build:
    defaults:
      run:
        working-directory: users-api

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
          cache-dependency-path: go.sum

      - name: Build
        run: make build

      - name: Test
        run: make test
